### ISSUE TITLE
No hardware accelerated video decoding and encoding

### ISSUE THREAD

**Issue by easy-and-simple** [radxa-build/rock-3a#7]
No hardware accelerated video decoding and encoding and video cant pe played and written
I installed video codecs and VLC but there is no video acceleration obviously because there is no video driver
Without video acceleration board is completely useless

**Comment by RadxaYuntian** [comment]
If you install one of our recent Debian Xfce build then Chromium and Parole media player support hardware accelerated video decoding out-of-the-box. There is a work-in-progress [`ffmpeg-jellyfin`](https://github.com/jellyfin/jellyfin-ffmpeg/pull/160) PR to support accelerated video encoding but we did not include it in our system.

Other software (like VLC) does not support either and that is expected behavior.

**Comment by easy-and-simple** [comment]
Hi
@RadxaYuntian  Thank you for replay and information supplied!
I need video acceleration mainly to use it in my AI/ML projects, so if ffmpeg-jellyfin supports hardware encoding/decoding this will be useful.
Do you have any idea is it possible to replace ffmpeg used by opencv with ffmpeg-jellyfin in order to achieve native hardware acceleration on opencv functions that use ffmpeg like videowriter function?
Also if you know some way to add hardware decoding to firefox I would try it.

**Comment by RadxaYuntian** [comment]
I'm no expert of OpenCV. Depending on how they use ffmpeg you will either install the Jellyfin version to the default location, or replace the code during compile time.

There is no way to support hardware decoding in Firefox since they only support VA-API. AFAICT there is no one working on a MPP to VA-API adapter.
