### ISSUE TITLE
Request: Panfrost drivers

### ISSUE THREAD

**Issue by gavan-x** [radxa-build/rock-3a#8]
This SBC was released 2021-08-25.... Yet still no actual GPU HW acceleration in any officially release RADXA images.
Is there a specific reason we have no GPU support?

**Comment by RadxaYuntian** [comment]
There is GPU support. We use Arm Mali driver. However, this only supports OpenGL ES. You can verify this with `glmark2-es2-x11` package.

Most normal desktop application use OpenGL though, which is only supported by Panfrost driver. This is on our to-do list.

**Comment by gavan-x** [comment]
glxinfo -B

Will display llvmpipe being used by the OS.
Llvmpipe is software accelerated not hardware.

Your definition of gpu support dosen't help the end user.

Armbian with gnome desktop is the only OS that is not utilizing llvmpipe with your SBC... and you guys aren't responsible for that.

- So when you guys do actually include gpu drivers that the OS actually uses feel free to paste the results of "glxinfo -B" and link the OS.


If you still need another perspective why customers need gpu a accelerated OS!

Web browser that leverage the gpu will not perform or run any webgl web apps at any acceptable level. Ai apps that will leverage a webcam and hardware acceleration will also not be in question.
When the OS is built correctly webgl aquarium run in on chrome will hit 40fps with 500 fishes selected. With the Rock 3A.

This level performance is only achieved by Armbian since they have included the GPU drivers.

It's is pointless to have such capable GPU on an SBC if the manufacturer is incapable of including actual GPU support, and not listening to the community and customers.

Everyone one know this. 

Hard kernel and Asus have been correctly including full gpu support in all their released SBC,just to name a few.

**Comment by RadxaYuntian** [comment]
> glxinfo -B
> 
> Will display llvmpipe being used by the OS.

You need to run `es2_info` to check OpenGL ES. `glxinfo` checks OpenGL, which as mentioned above, is not supported.

> Web browser that leverage the gpu will not perform or run any webgl web apps at any acceptable level.

The bundled Chromium is GPU accelerated. You can check with chrome://gpu.

> Hard kernel and Asus have been correctly including full gpu support in all their released SBC,just to name a few.

If you use opensource driver, you won't get OpenCL capability, so no it's still not full GPU support.

Rockchip SoC is first and foremost designed for Android, which uses OpenGL ES only. Since we tried to keep close with their SDK, we naturally uses their GPU driver first. Like I said, Panfrost is on our road map, but we don't have the resource to chase this right now.
